version: '3'
services:
  db:
    image: postgres
    volumes:
      - espertofit_personal_db:/var/lib/postgresql/data
  web:
    env_file:
      - '.env'
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 5000 -b '0.0.0.0'"
    container_name: esperto_fit_personal_web_1
    volumes:
      - .:/espertofit_personal
    ports:
      - "81:5000"
    depends_on:
      - db

volumes:
  espertofit_personal_db:

networks:
  default:
    external:
      name: esperto-network    