version: '3'
services:
  db:
    image: postgres
    volumes:
      - Personal:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "5000:3000"
    depends_on:
      - db
    volumes:
       - .:/espertofit_personal

volumes:
  Personal:

networks:
  default:
    external:
      name: EspertoFitNetwork